import { NextResponse } from "next/server";

// Static data — update when new types are added
const TYPES_DATA = {
  types: [
    // ── Tier 1: Full validation (supported now) ───────────────────────────
    {
      type: "Article",
      also_matches: ["NewsArticle", "BlogPosting", "TechArticle", "ScholarlyArticle"],
      status: "supported",
      tier: 1,
      validation_depth: "full",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/article",
      required_properties: ["headline", "author", "datePublished"],
      recommended_properties: ["image", "dateModified", "publisher", "description", "url"],
    },
    {
      type: "Product",
      also_matches: [],
      status: "supported",
      tier: 1,
      validation_depth: "full",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/product",
      required_properties: ["name"],
      recommended_properties: ["image", "offers", "description", "sku", "brand", "aggregateRating"],
    },
    {
      type: "LocalBusiness",
      also_matches: ["Restaurant", "FoodEstablishment", "Store", "Hotel", "LodgingBusiness", "MedicalBusiness"],
      status: "supported",
      tier: 1,
      validation_depth: "full",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/local-business",
      required_properties: ["name", "address"],
      recommended_properties: ["telephone", "openingHoursSpecification", "url", "image", "priceRange", "aggregateRating", "geo", "sameAs"],
    },
    {
      type: "Organization",
      also_matches: ["Corporation", "EducationalOrganization", "GovernmentOrganization", "NGO", "SportsOrganization", "NewsMediaOrganization"],
      status: "supported",
      tier: 1,
      validation_depth: "full",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/organization",
      required_properties: ["name"],
      recommended_properties: ["url", "logo", "sameAs", "contactPoint", "address", "description"],
    },
    {
      type: "BreadcrumbList",
      also_matches: [],
      status: "supported",
      tier: 1,
      validation_depth: "full",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/breadcrumb",
      required_properties: ["itemListElement"],
      recommended_properties: [],
    },
    {
      type: "WebSite",
      also_matches: [],
      status: "supported",
      tier: 1,
      validation_depth: "full",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/sitelinks-searchbox",
      required_properties: ["name", "url"],
      recommended_properties: ["potentialAction", "description", "sameAs"],
    },
    {
      type: "FAQPage",
      also_matches: [],
      status: "supported",
      tier: 1,
      validation_depth: "full",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/faqpage",
      required_properties: ["mainEntity"],
      recommended_properties: [],
      note: "Restricted to government and health websites since 2024.",
    },

    // ── Tier 2: Standard validation (coming soon) ─────────────────────────
    {
      type: "Review",
      also_matches: ["AggregateRating"],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/review-snippet",
      required_properties: ["itemReviewed", "reviewRating", "author"],
      recommended_properties: ["name", "reviewBody", "datePublished", "publisher"],
    },
    {
      type: "Recipe",
      also_matches: [],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/recipe",
      required_properties: ["name", "image", "recipeInstructions"],
      recommended_properties: ["author", "datePublished", "description", "prepTime", "cookTime", "totalTime", "recipeYield", "recipeIngredient", "aggregateRating"],
    },
    {
      type: "Event",
      also_matches: ["MusicEvent", "SportsEvent", "EducationEvent"],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/event",
      required_properties: ["name", "startDate", "location"],
      recommended_properties: ["endDate", "eventStatus", "eventAttendanceMode", "description", "image", "url", "offers", "performer", "organizer"],
    },
    {
      type: "VideoObject",
      also_matches: ["Clip"],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/video",
      required_properties: ["name", "description", "thumbnailUrl", "uploadDate"],
      recommended_properties: ["contentUrl", "embedUrl", "duration", "expires", "hasPart", "interactionStatistic", "publisher"],
    },
    {
      type: "SoftwareApplication",
      also_matches: ["WebApplication", "MobileApplication", "VideoGame"],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/software-app",
      required_properties: ["name", "applicationCategory", "operatingSystem"],
      recommended_properties: ["offers", "aggregateRating", "description", "url", "image", "downloadUrl", "softwareVersion"],
    },
    {
      type: "JobPosting",
      also_matches: [],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/job-posting",
      required_properties: ["title", "description", "hiringOrganization", "jobLocation", "datePosted"],
      recommended_properties: ["validThrough", "employmentType", "baseSalary", "identifier", "applicantLocationRequirements", "jobLocationType"],
    },
    {
      type: "Course",
      also_matches: ["CourseInstance"],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/course-info",
      required_properties: ["name", "description", "provider"],
      recommended_properties: ["url", "image", "hasCourseInstance", "courseCode", "educationalLevel", "offers"],
    },
    {
      type: "ItemList",
      also_matches: [],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/carousel",
      required_properties: ["itemListElement"],
      recommended_properties: ["name", "description", "numberOfItems", "url"],
    },
    {
      type: "QAPage",
      also_matches: [],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/qapage",
      required_properties: ["mainEntity"],
      recommended_properties: ["name", "description", "url"],
    },
    {
      type: "ProductGroup",
      also_matches: [],
      status: "supported",
      tier: 2,
      validation_depth: "standard",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/product-variants",
      required_properties: ["name", "hasVariant", "variesBy"],
      recommended_properties: ["description", "image", "brand", "sku", "url"],
    },

    // ── Tier 3: Basic validation (planned) ────────────────────────────────
    {
      type: "Book",
      also_matches: ["Audiobook"],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/book",
      required_properties: ["name", "author"],
      recommended_properties: ["isbn", "url", "image", "description", "workExample", "potentialAction"],
    },
    {
      type: "Dataset",
      also_matches: ["DataCatalog"],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/dataset",
      required_properties: ["name", "description"],
      recommended_properties: ["url", "creator", "license", "keywords", "distribution", "variableMeasured", "identifier"],
    },
    {
      type: "DiscussionForumPosting",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/discussion-forum",
      required_properties: ["headline", "url", "author", "datePublished"],
      recommended_properties: ["text", "image", "commentCount", "interactionStatistic", "dateModified"],
    },
    {
      type: "EmployerAggregateRating",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/employer-aggregate-rating",
      required_properties: ["itemReviewed", "ratingValue", "ratingCount"],
      recommended_properties: ["bestRating", "worstRating", "author"],
    },
    {
      type: "Movie",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/movie",
      required_properties: ["name"],
      recommended_properties: ["image", "description", "dateCreated", "director", "actor", "aggregateRating", "trailer", "contentRating", "url"],
    },
    {
      type: "ImageObject",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/image-license-metadata",
      required_properties: ["contentUrl"],
      recommended_properties: ["license", "acquireLicensePage", "creditText", "creator", "copyrightNotice", "name", "caption"],
    },
    {
      type: "ProfilePage",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/profile-page",
      required_properties: ["mainEntity"],
      recommended_properties: ["name", "description", "url", "image", "dateModified"],
    },
    {
      type: "MerchantReturnPolicy",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/merchant-listing",
      required_properties: ["applicableCountry", "returnPolicyCategory"],
      recommended_properties: ["merchantReturnDays", "returnMethod", "returnShippingFeesAmount", "refundType", "itemCondition"],
    },
    {
      type: "OfferShippingDetails",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/merchant-listing",
      required_properties: ["shippingRate", "shippingDestination", "deliveryTime"],
      recommended_properties: ["transitTimeLabel", "doesNotShip"],
    },
    {
      type: "ClaimReview",
      also_matches: [],
      status: "supported",
      tier: 3,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/factcheck",
      required_properties: ["claimReviewed", "reviewRating", "author", "itemReviewed"],
      recommended_properties: ["url", "datePublished", "name"],
      note: "Restricted to eligible fact-checking organizations.",
    },

    // ── Tier 4: Basic validation (future) ─────────────────────────────────
    {
      type: "MathSolver",
      also_matches: [],
      status: "supported",
      tier: 4,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/math-solvers",
      required_properties: ["name", "potentialAction"],
      recommended_properties: ["description", "url", "educationalLevel"],
    },
    {
      type: "Quiz",
      also_matches: [],
      status: "supported",
      tier: 4,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/education-qa",
      required_properties: ["name", "hasPart"],
      recommended_properties: ["about", "educationalLevel", "educationalAlignment", "description"],
    },
    {
      type: "LoyaltyProgram",
      also_matches: [],
      status: "supported",
      tier: 4,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/loyalty-program",
      required_properties: ["name", "hasMembershipDataType"],
      recommended_properties: ["url", "description", "programName", "membershipLevel"],
    },
    {
      type: "VacationRental",
      also_matches: ["LodgingBusiness", "Accommodation"],
      status: "supported",
      tier: 4,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/vacation-rental",
      required_properties: ["name", "description", "address"],
      recommended_properties: ["image", "offers", "numberOfRooms", "amenityFeature", "checkInTime", "checkOutTime"],
    },
    {
      type: "CreativeWork",
      also_matches: [],
      status: "supported",
      tier: 4,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/subscription-and-paywalled-content",
      required_properties: ["isAccessibleForFree", "hasPart"],
      recommended_properties: ["name", "description", "publisher", "url", "image"],
      note: "Used for subscription/paywalled content markup.",
    },

    // ── Deprecated: validated with deprecation warnings ───────────────────
    {
      type: "HowTo",
      also_matches: [],
      status: "deprecated",
      tier: null,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/how-to",
      required_properties: ["name", "step"],
      recommended_properties: ["description", "image", "totalTime"],
      note: "Retired by Google in August 2024. Validated with deprecation warning.",
    },
    {
      type: "SpecialAnnouncement",
      also_matches: [],
      status: "deprecated",
      tier: null,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/special-announcements",
      required_properties: ["name", "datePosted"],
      recommended_properties: ["expires", "text", "url", "category"],
      note: "Retired by Google in 2025. Validated with deprecation warning.",
    },
    {
      type: "Vehicle",
      also_matches: ["Car"],
      status: "deprecated",
      tier: null,
      validation_depth: "basic",
      google_docs_url: "https://developers.google.com/search/docs/appearance/structured-data/vehicle-listing",
      required_properties: ["name", "vehicleIdentificationNumber"],
      recommended_properties: ["description", "image", "offers", "brand", "mileageFromOdometer", "vehicleConfiguration"],
      note: "Vehicle Listing rich results retired by Google in 2025. Validated with deprecation warning.",
    },
  ],
  total_supported: 32,
  total_coming_soon: 0,
  total_planned: 0,
  total_deprecated: 3,
  schema_org_version: "V29.4",
  last_updated: "2026-03-18",
};

export async function GET() {
  return NextResponse.json(TYPES_DATA, {
    headers: {
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=3600",
    },
  });
}
